"""meat type added

Revision ID: 06038fe869ef
Revises: b8e894c957ec
Create Date: 2026-09-30 02:15:32.602585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06038fe869ef'
down_revision: Union[str, Sequence[str], None] = 'b8e894c957ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doners', sa.Column('doner_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('doners', sa.Column('meat_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('doners_doner_type_key'), 'doners', type_='unique')
    op.drop_column('doners', 'doner_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doners', sa.Column('doner_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('doners_doner_type_key'), 'doners', ['doner_type'], postgresql_nulls_not_distinct=False)
    op.drop_column('doners', 'meat_type')
    op.drop_column('doners', 'doner_name')
    # ### end Alembic commands ###
